version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      #- ./conf/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./html:/var/www/html
      - ./conf/site.conf:/etc/nginx/conf.d/default.conf
      #- ./html:/usr/share/nginx/html
      #- ./html:/var/www/html
  php-fpm:
    build:
      context: ./
      dockerfile: ./Dockerfile-fpm
    volumes:
      - ./html:/var/www/html
  composer:
    image: composer:latest
    working_dir: /var/www/html
    volumes:
      - ./html:/var/www/html
  dart-sass:
    #image: michalklempa/dart-sass
    build:
      context: ./
      dockerfile: ./Dockerfile-sass
    volumes:
      - ./html/sass:/sass
      - ./html/css:/css
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'test'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_DATABASE: 'test'
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
    mysqldata: {}